version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: kolbaska_db
      MYSQL_USER: kolbaska
      MYSQL_PASSWORD: kolbaska_password
      JWT_SECRET: superSecretThatHasToBeChangedInFuture
      API_BASEPATH: /
      API_BASEURL: https://api.maitsetuur.ee
    networks:
      - stack
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: kolbaska_db
      MYSQL_USER: kolbaska
      MYSQL_PASSWORD: kolbaska_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - stack

networks:
  stack:

volumes:
  db-data:
