version: '3'
services:
  react:
    build:
      context: Maitsetuur-frontend
      dockerfile: Dockerfile
    container_name: frontend
    command: sh script.sh
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8080/api/v1
    volumes:
      - ./Maitsetuur-frontend:/app
    working_dir: /app
    ports:
      - 3000:3000

  node-app:
    build:
      context: Maitsetuur-node-app
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    container_name: node-app
    command: sh script.sh
    volumes:
      - ./Maitsetuur-node-app:/usr/src/app
    networks:
      - microservices-network

  spring-boot:
    build:
      context: Maitsetuur-backend
      dockerfile: Dockerfile
    volumes:
      - ./Maitsetuur-backend:/app
    working_dir: /app
    container_name: backend
    command: sh script.sh
    environment:
      MYSQL_HOST: db
    ports:
      - 8080:8080
      - 5005:5005
    networks:
      - mysql-network
      - microservices-network

  db:
    image: mysql:8.0.33
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: kolbaska_db
      MYSQL_USER: kolbaska
      MYSQL_PASSWORD: kolbaska_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - mysql-network
networks:
  mysql-network: {}
  microservices-network: {}