version: '3'
services:
  react:
    build:
      context: Maitsetuur-frontend
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 3000:3000

  spring-boot:
    build:
      context: Maitsetuur-backend
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    command: sh script.sh
    ports:
      - 8080:8080
      - 5005:5005
    networks:
      - mysql-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: kolbaska_db
      MYSQL_USER: kolbaska
      MYSQL_PASSWORD: kolbaska_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - mysql-network
networks:
  mysql-network: {}