maitsetuur:
  database:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:kolbaska_db}
    username: ${MYSQL_USER:kolbaska}
    password: ${MYSQL_PASSWORD:kolbaska_password}
    pool-size: 30

spring:
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
  servlet:
    multipart:
      enabled: true
  mail:
    host: ${MAIL_HOST:yourdreams.today}
    port: 587
    username: ${MAIL_USERNAME:no-reply@yourdreams.today}
    password: ${MAIL_PASSWORD:zkAxT9QnoV9Rsib1}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:tvojrotebal}
  valid:
    for: 86000000
  issuer: ${JWT_ISSUER:kolbaska.com}

api:
  basepath: ${API_BASEPATH:/api/v1}
  baseurl: ${API_BASEURL:http://localhost:8080}

front:
  baseurl: ${FRONT_BASEURL:http://localhost:3000}

file-storage:
  basepath: ${UPLOAD_BASEPATH:/}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

management:
  endpoint:
    metrics:
      enabled: ${METRICS:false}
    prometheus:
      enabled: ${METRICS:false}
  endpoints:
    web:
      exposure:
        include: prometheus
logging:
  config: ${LOGBACK_PATH:classpath:logback.xml}

montonio:
  api:
    url: ${MONTONIO_API_URL:https://sandbox-stargate.montonio.com/api}
  accessKey: ${ACCESS_KEY:fab16ffa-8288-486c-9d16-4328c03b102b}
  secretKey: ${SECRET_KEY:jWycBGTgB+ypQ91gCnuovKUwrk2K1uUBxr2JSAtQXPQX}
